Added fashion mnist example project
iterative/example-repos-dev pull request #91
Opened 2021-09-07 10:33 UTC by tapadipti

2021-09-07 11:24 UTC, iesahin requested changes
Nice work @tapadipti. Thank you. 

Added a quick review. 

Is this something you have decided with @shcheklein ? We are trying to keep the number of example repositories minimum. I think he also may want to review this as well.

2021-09-07 11:24 UTC, iesahin commented on example-studio-all-fashion-mnist/code/params.yaml
> +  conv_activation: relu
newline 💅🏼 :)

2021-09-07 11:24 UTC, iesahin commented on example-studio-all-fashion-mnist/generator.sh
> +GIT_AUTHOR_NAME=$3
We are using "Olivaw" for the name and the email. You can see the other [`generate.sh`](https://github.com/iterative/example-repos-dev/blob/master/example-dvc-experiments/generate.bash#L21) for this.

2021-09-07 11:24 UTC, iesahin commented on example-studio-all-fashion-mnist/generator.sh
> +GIT_ORG=$1
I think you can keep this set. More generic scripts tend to fail more often IME.

2021-09-07 11:24 UTC, iesahin commented on example-studio-all-fashion-mnist/generator.sh
> +dvc repro train
It might be better to use `dvc exp run` to change the parameters.

2021-09-07 11:24 UTC, iesahin commented on example-studio-all-fashion-mnist/generator.sh
> +dvc run -n evaluate -d src/evaluate.py -d output/data.pkl -d output/model.h5 -M output/metrics.json --plots-no-cache output/predictions.json python src/evaluate.py
We use `dvc stage add` to add stages. `dvc run` is mostly deprecated.

2021-09-07 11:24 UTC, iesahin commented on example-studio-all-fashion-mnist/generator.sh
> +rm -fR build
newline :)

2021-09-07 11:24 UTC, iesahin commented on example-studio-all-fashion-mnist/generator.sh
> +hub delete -y $GIT_ORG/$REPO_NAME || true
I think `gh` is used instead of `hub` these days.

2021-09-07 14:23 UTC, tapadipti commented
> Is this something you have decided with @shcheklein ? We are trying to keep the number of example repositories minimum. I think he also may want to review this as well.

@iesahin I discussed this with @shcheklein and agreed that it's better not to create a new example project, but rather add useful stuff from this project into the Fashion Mnist example project that you are working on.

2021-09-09 15:06 UTC, iesahin reviewed
Thank you @tapadipti I added some more comments about incorporating this to `example-dvc-experiments`. Please let me know what you need for Studio and we'll apply those changes to `example-dvc-experiments`

2021-09-09 15:06 UTC, iesahin commented on example-studio-all-fashion-mnist/code/params.yaml
> +  batch_size: 128
We used to have many parameters but now we have two, the number of CNN units and the epochs. If you would like to have other parameters, I can add.

2021-09-09 15:06 UTC, iesahin commented on example-studio-all-fashion-mnist/code/requirements.txt
> +tensorflow==2.5.0
no need to have keras separate from tensorflow here. And I assume the user has already installed DVC on their system and don't add a (possibly conflicting) dvc to the requirements

2021-09-09 15:06 UTC, iesahin commented on example-studio-all-fashion-mnist/code/train_CNN.py
> +model.add(Dense(num_labels, activation='softmax'))
The model in `example-dvc-experiments` is similar to this.

2021-09-09 15:06 UTC, iesahin commented on example-studio-all-fashion-mnist/code/train_CNN.py
> +def history_to_csv(history):
Ah, yeah, you already saw it :)

2022-01-05 13:18 UTC, iesahin commented
Could we close this if it's no longer required? @tapadipti Thank you.

2022-01-05 13:27 UTC, tapadipti commented
@iesahin yes, I'll close it (coz we decided not to have too many example repos). Thanks for the reminder 🙏

2022-01-05 13:27 UTC, closed without merging